// teams.js
const teams = [
  "REAL MADRID", "BARCA", "ATLETICO", "MAN UTD", "MAN CITY", "LIVERPOOL",
  "ARSENAL", "CHELSEA", "TOTTENHAM", "PSG", "LYON", "BAYERN MUNCHEN",
  "DORTMUND", "FRANKFURT", "INTER MILAN", "AC MILAN", "JUVE", "NAPOLI",
  "ROMA", "RIVER PLATE", "FLAMENGO", "AL NASR", "AL HILAL", "BOCA JUNIOR"
];
